# site settings
title: 43 Work Space
subtitle: Coworking hub in Bengaluru 43
email: no-reply@43work.space
description: Coworking hub in Bengaluru 43
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: STE1, 232, 2nd floor, 9th Main Road, Kalyan Nagar
city: Bangalore
state: KA
zip_code: 560043
country: India
phone: +91-8861381443

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  Instagram: https://instagram.com/43workspace
  LinkedIn: https://linkedin.com/43workspace
  Twitter: https://twitter.com/43workspace
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
